version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-local-zapier
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database

  kafka:
    image: apache/kafka:3.7.1
    container_name: kafka-local-zapier
    ports:
      - "9092:9092"